--!strict
--■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
--  ◄► Title:       Config
--  ◄► Version:     1.0
--  ◄► Date:        17/07/2026
--  ◄► Author:      DeathToTheStadium
--  ◄► Description: Utilities/Types type definitions for framework-wide
--                  configuration values and options.
--■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
local Weapon = require(`../Types/Weapons`)

--■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
-- Constructor
--■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

type BaseConfig = {
	ViewModel: Model,
	Name: string,
	Damage: {
		Base: number,
		Limb: {
			Head: number?,
			Torso: number?,
			Arms: number?,
			Legs: number?,
			Feet: number?,
		}?
	},
	CameraInfo: {
		DefaultFOV: number?,
		ViewModelOffset: CFrame?,
	},
}


